/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import projeto.excepcoes.CasaException;
import projeto.excepcoes.EquipamentosDomesticosException;
import projeto.imports.Date;

public class grafica extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public grafica() {
        initComponents();
    }

    public static Rede rede = new Rede();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanelGrafo = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jPanelListagem = new javax.swing.JPanel();
        jButtonListarCasa = new javax.swing.JButton();
        jTextAreaListagem = new javax.swing.JTextArea();
        jButtonListarEqDomesticos = new javax.swing.JButton();
        jButtonListarEqProdutores = new javax.swing.JButton();
        jButtonListarPTransformacao = new javax.swing.JButton();
        jButtonListarProdEnergia = new javax.swing.JButton();
        jButtonLimparListagem = new javax.swing.JButton();
        jPanelEditar = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldEditaPotContador = new javax.swing.JTextField();
        jButtonEditarCasa = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaEditar = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldEditarIDZona = new javax.swing.JTextField();
        jPanelRemover = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldIDCasa = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jButtonRemoverCasa = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldEqDomestico = new javax.swing.JTextField();
        jButtonRemoverEqDomestico = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldIDEqProdutor = new javax.swing.JTextField();
        jButtonRemoverEqProdutor = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextFieldPTransformacao = new javax.swing.JTextField();
        jButtonRemoverPTransformacao = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextFieldProdEnergia = new javax.swing.JTextField();
        jButtonRemoverProdEnergia = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaRemover = new javax.swing.JTextArea();
        jPanelHistorico = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaHistorico = new javax.swing.JTextArea();
        jButtonListarHistorico = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldHistoricoED = new javax.swing.JTextField();
        jPanelInserir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldIDZona = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPotenciaContador = new javax.swing.JTextField();
        jButtonInserirCasa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTipoEqDom = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPotenciaNecess = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldIDCasaPertence = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButtonInserirEqDomestico = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTipoEqProdutor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldIDCasaPertenceEP = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButtonInserirEqProdutor = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldEnergiaDisponivel = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButtonPTransformacao = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldTipoProdEnergia = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jButtonProdEnergia = new javax.swing.JButton();
        jComboBoxCasa = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldIDEquipDomestico = new javax.swing.JTextField();
        jComboBoxEqDomestico = new javax.swing.JComboBox<>();
        jComboBoxEquipProdutor = new javax.swing.JComboBox<>();
        jComboBoxPTransformacao = new javax.swing.JComboBox<>();
        jComboBoxProdEnergia = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEqProdutor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldPotenciaProduzida = new javax.swing.JTextField();
        jButtonLimpar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldPotenciaProdE = new javax.swing.JTextField();
        jTextFieldEnergiaEmUtilizacao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel39.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        jLabel39.setText("Representação do grafo:");

        javax.swing.GroupLayout jPanelGrafoLayout = new javax.swing.GroupLayout(jPanelGrafo);
        jPanelGrafo.setLayout(jPanelGrafoLayout);
        jPanelGrafoLayout.setHorizontalGroup(
            jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrafoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39)
                .addContainerGap(820, Short.MAX_VALUE))
        );
        jPanelGrafoLayout.setVerticalGroup(
            jPanelGrafoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGrafoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel39)
                .addContainerGap(676, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Grafo", jPanelGrafo);

        jButtonListarCasa.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonListarCasa.setText("Listar Casas");
        jButtonListarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarCasaActionPerformed(evt);
            }
        });

        jTextAreaListagem.setEditable(false);
        jTextAreaListagem.setColumns(20);
        jTextAreaListagem.setRows(5);

        jButtonListarEqDomesticos.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonListarEqDomesticos.setText("Listar Equipamentos Domésticos");
        jButtonListarEqDomesticos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarEqDomesticosActionPerformed(evt);
            }
        });

        jButtonListarEqProdutores.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonListarEqProdutores.setText("Listar Equipamentos Produtores");
        jButtonListarEqProdutores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarEqProdutoresActionPerformed(evt);
            }
        });

        jButtonListarPTransformacao.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonListarPTransformacao.setText("Listar Postos Transformação");
        jButtonListarPTransformacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPTransformacaoActionPerformed(evt);
            }
        });

        jButtonListarProdEnergia.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jButtonListarProdEnergia.setText("Listar Produtores Energia");
        jButtonListarProdEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarProdEnergiaActionPerformed(evt);
            }
        });

        jButtonLimparListagem.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButtonLimparListagem.setText("Limpar");
        jButtonLimparListagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparListagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelListagemLayout = new javax.swing.GroupLayout(jPanelListagem);
        jPanelListagem.setLayout(jPanelListagemLayout);
        jPanelListagemLayout.setHorizontalGroup(
            jPanelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListarProdEnergia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimparListagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListarCasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListarEqProdutores, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jButtonListarPTransformacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonListarEqDomesticos, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jTextAreaListagem, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelListagemLayout.setVerticalGroup(
            jPanelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelListagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelListagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextAreaListagem, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelListagemLayout.createSequentialGroup()
                        .addComponent(jButtonListarCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonListarEqDomesticos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonListarEqProdutores, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonListarPTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonListarProdEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimparListagem, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Listagem", jPanelListagem);

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel23.setText("Editar Casa");

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel28.setText("Potência Contador");

        jButtonEditarCasa.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonEditarCasa.setText("Editar/Inserir");
        jButtonEditarCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarCasaActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel29.setText("Editar Equipamento Doméstico");

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel33.setText("Tipo Equipamento Doméstico");

        jLabel36.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel36.setText("Potencia Necessaria");

        jButton18.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton18.setText("Editar/Inserir");

        jLabel40.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel40.setText("Editar Equipamento Produtor");

        jLabel42.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel42.setText("Tipo Equipamento Produtor");

        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });

        jButton19.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton19.setText("Editar/Inserir");

        jLabel44.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel44.setText("Editar Posto Transformação");

        jLabel46.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel46.setText("Energia Disponivel");

        jButton20.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton20.setText("Editar/Inserir");

        jLabel47.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel47.setText("Inserir Produtor Energia");

        jLabel49.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel49.setText("Tipo Produtor Energia");

        jButton21.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButton21.setText("Editar/Inserir");

        jTextAreaEditar.setEditable(false);
        jTextAreaEditar.setColumns(20);
        jTextAreaEditar.setRows(5);
        jScrollPane4.setViewportView(jTextAreaEditar);

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel24.setText("Potência Produzida");

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel27.setText("Potência Produzida");

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel19.setText("ID Zona");

        javax.swing.GroupLayout jPanelEditarLayout = new javax.swing.GroupLayout(jPanelEditar);
        jPanelEditar.setLayout(jPanelEditarLayout);
        jPanelEditarLayout.setHorizontalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelEditarLayout.createSequentialGroup()
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEditarLayout.createSequentialGroup()
                                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField21)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel36)
                                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel47)
                            .addComponent(jLabel40)
                            .addComponent(jLabel44)
                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEditaPotContador, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEditarLayout.createSequentialGroup()
                                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel49)
                                    .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24)
                                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEditarCasa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(jPanelEditarLayout.createSequentialGroup()
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelEditarLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(84, 84, 84)
                                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEditarIDZona, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelEditarLayout.setVerticalGroup(
            jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEditarLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelEditarLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEditaPotContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonEditarCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEditarIDZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEditarLayout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel33))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addComponent(jLabel47)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(jLabel27))
                        .addGap(3, 3, 3)
                        .addGroup(jPanelEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );

        jTextField16.getAccessibleContext().setAccessibleName("");

        jTabbedPane4.addTab("Gestão - Edição", jPanelEditar);

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel21.setText("Remover Casa");

        jTextFieldIDCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDCasaActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel22.setText("ID Casa");

        jButtonRemoverCasa.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonRemoverCasa.setText("Remover");
        jButtonRemoverCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverCasaActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel25.setText("Remover Equipamento Doméstico");

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel26.setText("ID Equipamento Doméstico");

        jButtonRemoverEqDomestico.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonRemoverEqDomestico.setText("Remover");
        jButtonRemoverEqDomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverEqDomesticoActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel30.setText("Inserir Equipamento Produtor");

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel31.setText("ID Equipamento Produtor");

        jButtonRemoverEqProdutor.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonRemoverEqProdutor.setText("Remover");
        jButtonRemoverEqProdutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverEqProdutorActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel34.setText("Remover Posto Transformação");

        jLabel35.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel35.setText("ID Posto Transformação");

        jButtonRemoverPTransformacao.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonRemoverPTransformacao.setText("Remover");
        jButtonRemoverPTransformacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverPTransformacaoActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel37.setText("Remover Produtor Energia");

        jLabel38.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel38.setText("ID Produtor Energia");

        jButtonRemoverProdEnergia.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonRemoverProdEnergia.setText("Remover");
        jButtonRemoverProdEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverProdEnergiaActionPerformed(evt);
            }
        });

        jTextAreaRemover.setEditable(false);
        jTextAreaRemover.setColumns(20);
        jTextAreaRemover.setRows(5);
        jScrollPane3.setViewportView(jTextAreaRemover);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jTextFieldIDCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoverCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel34)
                    .addComponent(jLabel37)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                .addComponent(jTextFieldEqDomestico)
                                .addComponent(jTextFieldIDEqProdutor))
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRemoverEqProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRemoverEqDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldPTransformacao, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(jLabel35)
                            .addComponent(jLabel38)
                            .addComponent(jTextFieldProdEnergia))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRemoverProdEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRemoverPTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIDCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonRemoverCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldEqDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonRemoverEqDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIDEqProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonRemoverEqProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel34)
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonRemoverPTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldProdEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonRemoverProdEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelRemoverLayout = new javax.swing.GroupLayout(jPanelRemover);
        jPanelRemover.setLayout(jPanelRemoverLayout);
        jPanelRemoverLayout.setHorizontalGroup(
            jPanelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanelRemoverLayout.setVerticalGroup(
            jPanelRemoverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRemoverLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane4.addTab("Gestão - Remoção", jPanelRemover);

        jTextAreaHistorico.setColumns(20);
        jTextAreaHistorico.setRows(5);
        jScrollPane5.setViewportView(jTextAreaHistorico);

        jButtonListarHistorico.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonListarHistorico.setText("Apresentar Histórico");
        jButtonListarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarHistoricoActionPerformed(evt);
            }
        });

        jLabel32.setText("ID Equipamento Doméstico");

        javax.swing.GroupLayout jPanelHistoricoLayout = new javax.swing.GroupLayout(jPanelHistorico);
        jPanelHistorico.setLayout(jPanelHistoricoLayout);
        jPanelHistoricoLayout.setHorizontalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListarHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHistoricoED, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        jPanelHistoricoLayout.setVerticalGroup(
            jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHistoricoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelHistoricoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(jTextFieldHistoricoED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonListarHistorico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Histórico", jPanelHistorico);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel1.setText("Inserir Casa");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel3.setText("ID Zona");

        jTextFieldIDZona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDZonaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel4.setText("Potência Contador");

        jTextFieldPotenciaContador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPotenciaContadorActionPerformed(evt);
            }
        });

        jButtonInserirCasa.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonInserirCasa.setText("Inserir");
        jButtonInserirCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirCasaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel5.setText("Inserir Equipamento Doméstico");

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel7.setText("Tipo Equipamento Doméstico");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel8.setText("Potencia Necessaria");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel10.setText("ID Casa Pertence");

        jButtonInserirEqDomestico.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonInserirEqDomestico.setText("Inserir");
        jButtonInserirEqDomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirEqDomesticoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel11.setText("Inserir Equipamento Produtor");

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel13.setText("Tipo Equip. Produtor");

        jTextFieldIDCasaPertenceEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDCasaPertenceEPActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel14.setText("ID Casa Pertence");

        jButtonInserirEqProdutor.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonInserirEqProdutor.setText("Inserir");
        jButtonInserirEqProdutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirEqProdutorActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel15.setText("Inserir Posto Transformação");

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel17.setText("Energia Disponivel");

        jButtonPTransformacao.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonPTransformacao.setText("Inserir");
        jButtonPTransformacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPTransformacaoActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel18.setText("Inserir Produtor Energia");

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel20.setText("Tipo Produtor Energia");

        jButtonProdEnergia.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonProdEnergia.setText("Inserir");
        jButtonProdEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProdEnergiaActionPerformed(evt);
            }
        });

        jComboBoxCasa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCasaItemStateChanged(evt);
            }
        });
        jComboBoxCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCasaActionPerformed(evt);
            }
        });

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel2.setText("ID Equipamento Doméstico");

        jComboBoxEqDomestico.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEqDomesticoItemStateChanged(evt);
            }
        });
        jComboBoxEqDomestico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEqDomesticoActionPerformed(evt);
            }
        });

        jComboBoxEquipProdutor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEquipProdutorItemStateChanged(evt);
            }
        });
        jComboBoxEquipProdutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEquipProdutorActionPerformed(evt);
            }
        });

        jComboBoxPTransformacao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxPTransformacaoItemStateChanged(evt);
            }
        });

        jComboBoxProdEnergia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxProdEnergiaItemStateChanged(evt);
            }
        });
        jComboBoxProdEnergia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProdEnergiaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel6.setText("ID Equipamento Produtor");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel12.setText("Potencia Produzida");

        jButtonLimpar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 11)); // NOI18N
        jLabel16.setText("Potencia Produzida");

        jLabel9.setText("EnergiaEmUtilizacao");

        javax.swing.GroupLayout jPanelInserirLayout = new javax.swing.GroupLayout(jPanelInserir);
        jPanelInserir.setLayout(jPanelInserirLayout);
        jPanelInserirLayout.setHorizontalGroup(
            jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInserirLayout.createSequentialGroup()
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel11)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelInserirLayout.createSequentialGroup()
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldIDZona, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addComponent(jTextFieldIDEquipDomestico)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextFieldEqProdutor))
                                    .addComponent(jTextFieldPotenciaNecess, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(jTextFieldTipoProdEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEnergiaDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanelInserirLayout.createSequentialGroup()
                                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel16)
                                            .addComponent(jTextFieldPotenciaContador, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                            .addComponent(jTextFieldTipoEqDom)
                                            .addComponent(jTextFieldIDCasaPertence, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                            .addComponent(jLabel10)
                                            .addComponent(jTextFieldTipoEqProdutor, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12)
                                            .addComponent(jTextFieldPotenciaProduzida)
                                            .addComponent(jTextFieldPotenciaProdE)
                                            .addComponent(jTextFieldEnergiaEmUtilizacao))
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonInserirCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonPTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonProdEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonInserirEqProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonInserirEqDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(37, 37, 37)
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEquipProdutor, 0, 127, Short.MAX_VALUE)
                            .addComponent(jComboBoxEqDomestico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxProdEnergia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCasa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxPTransformacao, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25))
                    .addGroup(jPanelInserirLayout.createSequentialGroup()
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIDCasaPertenceEP, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelInserirLayout.setVerticalGroup(
            jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInserirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInserirLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIDZona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPotenciaContador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonInserirCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInserirLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonInserirEqDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxEqDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(jLabel11))
                            .addGroup(jPanelInserirLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIDEquipDomestico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldTipoEqDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldIDCasaPertence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPotenciaNecess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelInserirLayout.createSequentialGroup()
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTipoEqProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEqProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel12)))
                            .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonInserirEqProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxEquipProdutor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldIDCasaPertenceEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldPotenciaProduzida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInserirLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldTipoProdEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPotenciaProdE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelInserirLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonProdEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxProdEnergia, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel15)
                        .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelInserirLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxPTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonPTransformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelInserirLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanelInserirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldEnergiaDisponivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldEnergiaEmUtilizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanelInserirLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpar)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Gestão - Inserção", jPanelInserir);

        jMenu1.setText("Ficheiro");

        jMenu3.setText("Novo");
        jMenu1.add(jMenu3);

        jMenu4.setText("Abrir");
        jMenu1.add(jMenu4);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonListarPTransformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPTransformacaoActionPerformed
        for (Integer pt : rede.getPostosTransformacaoST().keys()) {
            PostoTransformacao postoTransformacao = (PostoTransformacao) rede.getPostosTransformacaoST().get(pt);
            jTextAreaListagem.append(" " + postoTransformacao.getIdPostoTransformacao() + " " + postoTransformacao.getEnergiaDisponivel() + "\n");
        }
    }//GEN-LAST:event_jButtonListarPTransformacaoActionPerformed

    private void jButtonListarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarCasaActionPerformed
        for (Integer c : rede.getCasasST().keys()) {
            Casa casa = (Casa) rede.getCasasST().get(c);
            jTextAreaListagem.append(" " + casa.getIdCasa() + " " + casa.getPotenciaContador() + " " + casa.getSomaPotenciasEquipamentosDomesticos() + " "
                    + casa.getSomaEnergiaEquipamentosProdutores() + " " + casa.getIdZona() + "\n");
        }
    }//GEN-LAST:event_jButtonListarCasaActionPerformed

    private void jTextFieldIDCasaPertenceEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDCasaPertenceEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDCasaPertenceEPActionPerformed

    private void jTextFieldIDCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDCasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDCasaActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    //Botão inserir Casa
    private void jButtonInserirCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirCasaActionPerformed
        int idZona = Integer.parseInt(jTextFieldIDZona.getText());
        Float potenciaContador = Float.parseFloat(jTextFieldPotenciaContador.getText());
        float somaPotenciasEquipamentosDomesticos = 0.0f;
        float somaEnergiaEquipamentosProdutores = 0.0f;

        Casa c = new Casa(potenciaContador, somaPotenciasEquipamentosDomesticos, somaEnergiaEquipamentosProdutores, idZona);
        rede.getCasasST().put(c.getIdCasa(), c);
        this.jComboBoxCasa.addItem(Integer.toString(c.getIdCasa()));

        //Limpa as jTextField após inserção.
        this.jTextFieldIDZona.setText("");
        this.jTextFieldPotenciaContador.setText("");
    }//GEN-LAST:event_jButtonInserirCasaActionPerformed

    private void jComboBoxCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCasaActionPerformed

    }//GEN-LAST:event_jComboBoxCasaActionPerformed

    private void jTextFieldIDZonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDZonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDZonaActionPerformed

    private void jTextFieldPotenciaContadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPotenciaContadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPotenciaContadorActionPerformed

    private void jComboBoxCasaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCasaItemStateChanged
        int id = Integer.parseInt(evt.getItem().toString());
        Casa c = rede.getCasasST().get(id);
        this.jTextArea2.setText(c.toString());

    }//GEN-LAST:event_jComboBoxCasaItemStateChanged

    private void jButtonInserirEqDomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirEqDomesticoActionPerformed
        int idEquipamentoDomestico = Integer.parseInt(jTextFieldIDEquipDomestico.getText());
        String tipoEquipamentoDomestico = jTextFieldTipoEqDom.getText();
        Float potenciaNecessaria = Float.parseFloat(jTextFieldPotenciaNecess.getText());
        int casaAQuePertence = Integer.parseInt(jTextFieldIDCasaPertence.getText());
        Date dataLigado = new Date(0, 0, 0, 0, 0, 0);
        boolean ligado = false;

        EquipamentoDomestico ed = new EquipamentoDomestico(idEquipamentoDomestico, tipoEquipamentoDomestico, potenciaNecessaria, ligado, dataLigado, casaAQuePertence);
        rede.getEquipamentosDomesticosST().put(ed.getIdEquipamentoDomestico(), ed);
        this.jComboBoxEqDomestico.addItem(Integer.toString(ed.getIdEquipamentoDomestico()));

        //Limpa as jTextField após inserção.
        this.jTextFieldIDEquipDomestico.setText("");
        this.jTextFieldTipoEqDom.setText("");
        this.jTextFieldPotenciaNecess.setText("");
        this.jTextFieldIDCasaPertence.setText("");
    }//GEN-LAST:event_jButtonInserirEqDomesticoActionPerformed

    private void jComboBoxEqDomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEqDomesticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEqDomesticoActionPerformed

    private void jComboBoxEqDomesticoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEqDomesticoItemStateChanged
        int id = Integer.parseInt(evt.getItem().toString());
        EquipamentoDomestico ed = rede.getEquipamentosDomesticosST().get(id);
        this.jTextArea2.setText(ed.toString());
    }//GEN-LAST:event_jComboBoxEqDomesticoItemStateChanged

    private void jButtonInserirEqProdutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirEqProdutorActionPerformed
        int idEquipamentoProdutor = Integer.parseInt(jTextFieldEqProdutor.getText());
        String tipoEquipamentoProdutor = jTextFieldTipoEqProdutor.getText();
        Float potenciaProduzida = Float.parseFloat(jTextFieldPotenciaProduzida.getText());
        int casaAQuePertence = Integer.parseInt(jTextFieldIDCasaPertenceEP.getText());

        EquipamentoProdutor ep = new EquipamentoProdutor(idEquipamentoProdutor, tipoEquipamentoProdutor, potenciaProduzida, casaAQuePertence);
        rede.getEquipamentosProdutoresST().put(ep.getIdEquipamentoProdutor(), ep);
        this.jComboBoxEquipProdutor.addItem(Integer.toString(ep.getIdEquipamentoProdutor()));

        //Limpa as jTextField após inserção.
        this.jTextFieldEqProdutor.setText("");
        this.jTextFieldTipoEqProdutor.setText("");
        this.jTextFieldIDCasaPertenceEP.setText("");
        this.jTextFieldPotenciaProduzida.setText("");
    }//GEN-LAST:event_jButtonInserirEqProdutorActionPerformed


    private void jComboBoxEquipProdutorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEquipProdutorItemStateChanged
        int id = Integer.parseInt(evt.getItem().toString());
        EquipamentoProdutor ep = rede.getEquipamentosProdutoresST().get(id);
        this.jTextArea2.setText(ep.toString());
    }//GEN-LAST:event_jComboBoxEquipProdutorItemStateChanged

    private void jButtonPTransformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPTransformacaoActionPerformed
        Float energiaDisponivel = Float.parseFloat(jTextFieldEnergiaDisponivel.getText());
        Float energiaEmUtilizacao = Float.parseFloat(jTextFieldEnergiaEmUtilizacao.getText());

        PostoTransformacao pt = new PostoTransformacao(energiaDisponivel, energiaEmUtilizacao);
        rede.getPostosTransformacaoST().put(pt.getIdPostoTransformacao(), pt);
        this.jComboBoxPTransformacao.addItem(Integer.toString(pt.getIdPostoTransformacao()));

        //Limpa as jTextField após inserção.
        this.jTextFieldEnergiaDisponivel.setText("");
    }//GEN-LAST:event_jButtonPTransformacaoActionPerformed

    private void jComboBoxPTransformacaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxPTransformacaoItemStateChanged
        int id = Integer.parseInt(evt.getItem().toString());
        PostoTransformacao pt = rede.getPostosTransformacaoST().get(id);
        this.jTextArea2.setText(pt.toString());
    }//GEN-LAST:event_jComboBoxPTransformacaoItemStateChanged

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        this.jTextArea2.setText("");
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonProdEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProdEnergiaActionPerformed
        String tipoProdutorEnergia = jTextFieldTipoProdEnergia.getText();
        Float potenciaProduzida = Float.parseFloat(jTextFieldPotenciaProdE.getText());

        ProdutorEnergia pe = new ProdutorEnergia(tipoProdutorEnergia, potenciaProduzida);
        rede.getProdutoresEnergiaST().put(pe.getIdProdutorEnergia(), pe);
        this.jComboBoxProdEnergia.addItem(Integer.toString(pe.getIdProdutorEnergia()));

        //Limpa as jTextField após inserção.
        this.jTextFieldTipoProdEnergia.setText("");
        this.jTextFieldPotenciaProdE.setText("");
    }//GEN-LAST:event_jButtonProdEnergiaActionPerformed

    private void jComboBoxProdEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProdEnergiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdEnergiaActionPerformed

    private void jComboBoxProdEnergiaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxProdEnergiaItemStateChanged
        int id = Integer.parseInt(evt.getItem().toString());
        ProdutorEnergia ep = rede.getProdutoresEnergiaST().get(id);
        this.jTextArea2.setText(ep.toString());
    }//GEN-LAST:event_jComboBoxProdEnergiaItemStateChanged

    private void jButtonListarEqDomesticosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEqDomesticosActionPerformed
        for (Integer ed : rede.getEquipamentosDomesticosST().keys()) {
            EquipamentoDomestico equipamentoDomestico = (EquipamentoDomestico) rede.getEquipamentosDomesticosST().get(ed);
            jTextAreaListagem.append(" " + equipamentoDomestico.getIdEquipamentoDomestico() + " " + equipamentoDomestico.getTipoEquipamentoDomestico() + " " + equipamentoDomestico.getPotenciaNecessaria() + " "
                    + " " + equipamentoDomestico.getDataLigado() + " " + equipamentoDomestico.getCasaAQuePertence() + "\n");
        }
    }//GEN-LAST:event_jButtonListarEqDomesticosActionPerformed

    private void jButtonListarEqProdutoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEqProdutoresActionPerformed
        // TODO add your handling code here:
        for (Integer ep : rede.getEquipamentosProdutoresST().keys()) {
            EquipamentoProdutor equipamentoProdutor = (EquipamentoProdutor) rede.getEquipamentosProdutoresST().get(ep);
            jTextAreaListagem.append(" " + equipamentoProdutor.getIdEquipamentoProdutor() + " " + equipamentoProdutor.getTipoEquipamentoProdutor() + " " + equipamentoProdutor.getPotenciaProduzida() + " "
                    + " " + equipamentoProdutor.getCasaAQuePertence() + "\n");
        }
    }//GEN-LAST:event_jButtonListarEqProdutoresActionPerformed

    private void jButtonListarProdEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarProdEnergiaActionPerformed
        for (Integer pe : rede.getProdutoresEnergiaST().keys()) {
            ProdutorEnergia produtorEnergia = (ProdutorEnergia) rede.getProdutoresEnergiaST().get(pe);
            jTextAreaListagem.append(" " + produtorEnergia.getIdProdutorEnergia() + " " + produtorEnergia.getTipoProdutorEnergia() + " " + produtorEnergia.getPotenciaProduzida() + "\n");
        }
    }//GEN-LAST:event_jButtonListarProdEnergiaActionPerformed

    private void jButtonRemoverCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverCasaActionPerformed
        int idCasa = Integer.parseInt(jTextFieldIDCasa.getText());
        rede.removerCasa(idCasa);
        jTextAreaRemover.append("Casa removida com sucesso! \n");

        //Limpa as jTextField após inserção.
        this.jTextFieldIDCasa.setText("");
    }//GEN-LAST:event_jButtonRemoverCasaActionPerformed

    private void jButtonRemoverEqDomesticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverEqDomesticoActionPerformed
        int idEquipamentoDomestico = Integer.parseInt(jTextFieldEqDomestico.getText());
        //Remove da RedBlack na classe Casa
        for (Integer i : rede.getCasasST().keys()) {
            Casa c = rede.getCasasST().get(i);
            c.removerEquipamentoDomestico(idEquipamentoDomestico);
        }
        //Remove da RedBlack auxiliar na classe Rede
        for (Integer j : rede.getEquipamentosDomesticosST().keys()) {
            if (rede.getEquipamentosDomesticosST().get(j).getIdEquipamentoDomestico() == (idEquipamentoDomestico)) {
                rede.getEquipamentosDomesticosST().delete(j);
            }
        }
        jTextAreaRemover.setText("Equipamento doméstico removido com sucesso! \n");

        //Limpa as jTextField após inserção.
        this.jTextFieldEqDomestico.setText("");
    }//GEN-LAST:event_jButtonRemoverEqDomesticoActionPerformed

    private void jButtonRemoverEqProdutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverEqProdutorActionPerformed
        int idEquipamentoProdutor = Integer.parseInt(jTextFieldIDEqProdutor.getText());
        //String idEquipamentoProdutorStr = jTextFieldIDEqProdutor.getText();
        //Remove da RedBlack na classe Casa
        for (Integer i : rede.getCasasST().keys()) {
            Casa c = rede.getCasasST().get(i);
            c.removerEquipamentoProdutor(idEquipamentoProdutor);
        }
        //Remove da RedBlack auxiliar na classe Rede
        for (Integer j : rede.getEquipamentosProdutoresST().keys()) {
            if (rede.getEquipamentosProdutoresST().get(j).getIdEquipamentoProdutor() == (idEquipamentoProdutor)) {
                rede.getEquipamentosProdutoresST().delete(j);
            }
        }
        /*
        //Remover da combobox???
        int comboIndex = 0;
        while(jComboBoxEquipProdutor.getItemAt(comboIndex) != null){
            if(Integer.parseInt(jComboBoxEquipProdutor.getItemAt(comboIndex)) == idEquipamentoProdutor){
                jComboBoxEquipProdutor.removeItemAt(comboIndex);
                break;
            }
        }
         */

        jTextArea2.setText("");
        jTextAreaRemover.setText("Equipamento produtor removido com sucesso! \n");
    }//GEN-LAST:event_jButtonRemoverEqProdutorActionPerformed

    private void jButtonRemoverPTransformacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverPTransformacaoActionPerformed
        int idPostoTransformacao = Integer.parseInt(jButtonRemoverPTransformacao.getText());
        rede.removerPostoTransformacao(idPostoTransformacao);
        jTextAreaRemover.append("Posto transformação removido com sucesso! \n");

        //Limpa as jTextField após inserção.
        this.jButtonRemoverPTransformacao.setText("");
    }//GEN-LAST:event_jButtonRemoverPTransformacaoActionPerformed

    private void jButtonRemoverProdEnergiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverProdEnergiaActionPerformed
        int idProdutorEnergia = Integer.parseInt(jButtonRemoverProdEnergia.getText());
        rede.removerProdutorEnergia(idProdutorEnergia);
        jTextAreaRemover.append("Produtor Energia removido com sucesso! \n");

        //Limpa as jTextField após inserção.
        this.jButtonRemoverProdEnergia.setText("");
    }//GEN-LAST:event_jButtonRemoverProdEnergiaActionPerformed

    private void jButtonListarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarHistoricoActionPerformed
        int idEquipamentoDomestico = Integer.parseInt(jButtonRemoverProdEnergia.getText());
        for(Integer i : rede.getCasasST().keys()){
            Casa c = rede.getCasasST().get(i);
            for(Integer j : c.getEquipamentosDomesticosST().keys()){
                EquipamentoDomestico ed = c.getEquipamentosDomesticosST().get(j);
                if(ed.getIdEquipamentoDomestico() == idEquipamentoDomestico){
                    for(Integer k : ed.getHistoricoUtilizacaoST().keys()){
                        HistoricoUtilizacao hu = ed.getHistoricoUtilizacaoST().get(k);
                        this.jTextAreaHistorico.setText(hu.toString());
                    }
                }
            }
        }
    }//GEN-LAST:event_jButtonListarHistoricoActionPerformed

    private void jButtonEditarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarCasaActionPerformed

    }//GEN-LAST:event_jButtonEditarCasaActionPerformed

    private void jComboBoxEquipProdutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEquipProdutorActionPerformed

    }//GEN-LAST:event_jComboBoxEquipProdutorActionPerformed

    private void jButtonLimparListagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparListagemActionPerformed
        this.jTextAreaListagem.setText("");
    }//GEN-LAST:event_jButtonLimparListagemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        rede.dump();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     * @throws projeto.excepcoes.CasaException
     */
    public static void main(String args[]) throws CasaException, EquipamentosDomesticosException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grafica().setVisible(true);
            }
        });
        
        rede.carregarProdutoresEnergiaFicheiro(".//src//projeto//data//produtores_energia.txt");
        rede.carregarPostosTransformacaoFicheiro(".//src//projeto//data//postos_transformacao.txt");
        rede.carregarCasasFicheiro(".//src//projeto//data//casas.txt");
        rede.carregarEquipamentosProdutoresFicheiro(".//src//projeto//data//equipamentos_produtores.txt");
        rede.carregarEquipamentosDomesticosFicheiro(".//src//projeto//data//equipamentos_domesticos.txt");
        rede.carregarHistoricosUtilizacaoFicheiro(".//src//projeto//data//historicos_utilizacao.txt");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButtonEditarCasa;
    private javax.swing.JButton jButtonInserirCasa;
    private javax.swing.JButton jButtonInserirEqDomestico;
    private javax.swing.JButton jButtonInserirEqProdutor;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonLimparListagem;
    private javax.swing.JButton jButtonListarCasa;
    private javax.swing.JButton jButtonListarEqDomesticos;
    private javax.swing.JButton jButtonListarEqProdutores;
    private javax.swing.JButton jButtonListarHistorico;
    private javax.swing.JButton jButtonListarPTransformacao;
    private javax.swing.JButton jButtonListarProdEnergia;
    private javax.swing.JButton jButtonPTransformacao;
    private javax.swing.JButton jButtonProdEnergia;
    private javax.swing.JButton jButtonRemoverCasa;
    private javax.swing.JButton jButtonRemoverEqDomestico;
    private javax.swing.JButton jButtonRemoverEqProdutor;
    private javax.swing.JButton jButtonRemoverPTransformacao;
    private javax.swing.JButton jButtonRemoverProdEnergia;
    private javax.swing.JComboBox<String> jComboBoxCasa;
    private javax.swing.JComboBox<String> jComboBoxEqDomestico;
    private javax.swing.JComboBox<String> jComboBoxEquipProdutor;
    private javax.swing.JComboBox<String> jComboBoxPTransformacao;
    private javax.swing.JComboBox<String> jComboBoxProdEnergia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanelEditar;
    private javax.swing.JPanel jPanelGrafo;
    private javax.swing.JPanel jPanelHistorico;
    private javax.swing.JPanel jPanelInserir;
    private javax.swing.JPanel jPanelListagem;
    private javax.swing.JPanel jPanelRemover;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextAreaEditar;
    private javax.swing.JTextArea jTextAreaHistorico;
    private javax.swing.JTextArea jTextAreaListagem;
    private javax.swing.JTextArea jTextAreaRemover;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextFieldEditaPotContador;
    private javax.swing.JTextField jTextFieldEditarIDZona;
    private javax.swing.JTextField jTextFieldEnergiaDisponivel;
    private javax.swing.JTextField jTextFieldEnergiaEmUtilizacao;
    private javax.swing.JTextField jTextFieldEqDomestico;
    private javax.swing.JTextField jTextFieldEqProdutor;
    private javax.swing.JTextField jTextFieldHistoricoED;
    private javax.swing.JTextField jTextFieldIDCasa;
    private javax.swing.JTextField jTextFieldIDCasaPertence;
    private javax.swing.JTextField jTextFieldIDCasaPertenceEP;
    private javax.swing.JTextField jTextFieldIDEqProdutor;
    private javax.swing.JTextField jTextFieldIDEquipDomestico;
    private javax.swing.JTextField jTextFieldIDZona;
    private javax.swing.JTextField jTextFieldPTransformacao;
    private javax.swing.JTextField jTextFieldPotenciaContador;
    private javax.swing.JTextField jTextFieldPotenciaNecess;
    private javax.swing.JTextField jTextFieldPotenciaProdE;
    private javax.swing.JTextField jTextFieldPotenciaProduzida;
    private javax.swing.JTextField jTextFieldProdEnergia;
    private javax.swing.JTextField jTextFieldTipoEqDom;
    private javax.swing.JTextField jTextFieldTipoEqProdutor;
    private javax.swing.JTextField jTextFieldTipoProdEnergia;
    // End of variables declaration//GEN-END:variables
}
